# Multiple readings related to engine temperatures

std_msgs/Header header  # timestamp of the measurement

float64 coolant_temperature             # [°C] engine coolant temperature reading

float64 fuel_temperature                # [°C] engine fuel temperature reading

float64 oil_temperature                 # [°C] engine oil temperature reading

float64 intercooler_temperature         # [°C] engine intercooler temperature reading

float64 turbocharger_oil_temperature    # [°C] engine turbocharger lubricant temperature reading